### ISSUE TITLE
Genin Guard Clones Invincibility

### ISSUE THREAD

**Issue by Noxtyr** [douglasparker/naruto-evolution-community#101]
### Bug Report

Genin Guard made clones. I killed Genin Guard. His clone stayed and are immortal, derpy (don't do anything), naked and menacing.

### Expected Behavior

Clones disappear after death of caster.

### Steps to Reproduce

above

### Game Version

2.4.16

### BYOND Server Version

514.1566

### BYOND Client Version

514.1566

### Error Logs

---

### Screenshots

![image](https://user-images.githubusercontent.com/106283400/172838220-de020039-26d8-46da-8a0c-b635b1977b0b.png)

### Form Completion and Accuracy

- [X] I confirm that this form has been completed in full and is accurate to the best of my knowledge.

**Comment by douglasparker** [comment]
Guards have major fixes coming in the next release.

**Comment by douglasparker** [comment]
This was fixed in commit douglasparker/naruto-evolution#668a4757f791a2aa3c82b25d8b1bcc7344c7097a and will be released in v2.5.0.
