### ISSUE TITLE
Leaf hurricane icon not visible

### ISSUE THREAD

**Issue by YaBoiKino** [douglasparker/naruto-evolution-community#14]
Leaf green hurricane icon not visble

**Comment by IllusiveBIair** [comment]
It should only become visible once the jutsu is level 4. Please let me know if this is not the case.

**Comment by YaBoiKino** [comment]
It isnt
and it doesnt send ppl fly away anymore either

**Comment by douglasparker** [comment]
What do you mean that it's not visible? Are we talking about the cooldown, the icon in the skill tree, an animation or effect that plays when using the skill?

**Comment by Juxnist** [comment]
The animation that plays when using the skill. The animation became visible at level 3 for me and then vanished entirely upon reaching level 4.

**Comment by IllusiveBIair** [comment]
The removal of the knockback effect is an intentional change. As for the whirlwind animation, it would appear it's unintentionally showing at level 3 instead of 4. It's a low-priority bug but I will address it at some point, thank you for the info.
