### ISSUE TITLE
ShiShi Rendan Cooldown

### ISSUE THREAD

**Issue by Juxnist** [douglasparker/naruto-evolution-community#81]
### Bug Report

When you use this jutsu without a target it will output "You need to have a Target to perform ShiShi Rendan" but it will still trigger the 10 second cooldown for the skill as if you used it.

### Expected Behavior

I expect it to not trigger a cooldown since it wasn't actually executed.

### Steps to Reproduce

1. Have no target selected.
2.  Use ShiShi Rendan.

### Game Version

2.14.16

### BYOND Server Version

N/A

### BYOND Client Version

514.1584

### Form Completion and Accuracy

- [X] I confirm that this form has been completed in full and is accurate to the best of my knowledge.

**Comment by douglasparker** [comment]
This issue was resolved in commit douglasparker/naruto-evolution@1763ee30842c2ff7ce2c22f102060a15a5706bce
