### ISSUE TITLE
Advanced Body Replacement Jutsu

### ISSUE THREAD

**Issue by Noxtyr** [douglasparker/naruto-evolution-community#85]
### Bug Report

Doesn't lvl up mastery.

### Expected Behavior

Should be able to be mastered for quicker cooldown or something.

### Steps to Reproduce

E+E+Space

### Game Version

2.4.16

### BYOND Server Version

514.1566

### BYOND Client Version

514.1566

### Error Logs

none

### Screenshots

none

### Form Completion and Accuracy

- [X] I confirm that this form has been completed in full and is accurate to the best of my knowledge.

**Comment by Juxnist** [comment]
#77 Was already reported awhile back.
